### ISSUE TITLE
[Suggestion] Extern<T> type from 'haxe-extype' lib as an alternative to Record type.

### ISSUE THREAD

**Issue by djaonourside** [kLabz/haxe-material-ui#1]
IMHO, Using Extern<T> with @:native meta from [haxe-extype](https://github.com/DenkiYagi/haxe-extype) looks more clearly than Record type.

**Comment by kLabz** [comment]
But they're different things.

`Record<T>` is from the typescript [type with the same name](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#partial-readonly-record-and-pick), which is in fact used under the hood for these `classes` props too (see [here](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/withStyles/withStyles.d.ts#L58)).

It generates a type like this:
```haxe
typedef Record_T = {
  ?someClass:String,
  ?someOtherClass:String
}
```

From an enum abstract like this:
```haxe
enum abstract T(String) to String {
  var SomeClass = "someClass";
  var SomeOtherClass = "someOtherClass";
}
```
(which can also be used as an enum abstract somewhere else in the code)

**Comment by djaonourside** [comment]
I don't think there are different. I think they both solve a problem of haxe reserved keywords in anonymous objects.

```
typedef Classes = 
{
  someClass: String,
  someOtherClass: String,
 @:native('default')
  default_: String
}
...
var classes: Extern<Classes>; 
```

But it's ok. It was just a suggestion:)

**Comment by kLabz** [comment]
Using `Record<T>` is not meant to solve this problem, it's meant to generate the type from enum abstract values (which are not used anywhere else atm in public code, but that will probably change).

**Comment by djaonourside** [comment]
I see. Thank you for explaining this thing)
