### ISSUE TITLE
stickyHeader prop on Table

### ISSUE THREAD

**Issue by bablukid** [kLabz/haxe-material-ui#10]
Yo !

would be nice to have  stickyHeader prop on Table component.
like in https://v4-7-2.material-ui.com/components/tables/#fixed-header

It seems also that in mui 4.8.3, there is a new component named TableContainer.

**Comment by kLabz** [comment]
`stickyHeader` is already available: https://github.com/kLabz/haxe-material-ui/blob/master/src/mui/core/Table.hx#L16

Yeah I still need to add changes from 4.8.x

**Comment by bablukid** [comment]
ok, sorry I didnt have the latest version.

thx
